### PR TITLE
validation script for all thresholds

### PR DESCRIPTION
**Pull request by mie-h**

### CODE REVIEW

**Comment by LucileTech** [comment]
Awesome scripts and organization, thank you!

I created my all_prediction.jsonl file using your script on the notebook, and performed your model evaluation scripts on it. 
I modified a bit 'main' so it prints the harassment data and so the created files go into a folder named just like the jsonl file used in the script. I thought it was a good way to test the script with our various data and keep track of the differences. What do you think?

Screenshot 2023-12-19 at 09 04 38

I also replaced our name with a variable as discussed last week.

**Comment by LucileTech** [comment]
I added Mie Script for jsonl file creation, created a congif file with the name variable, and cleaned up notebooks from output and prints

**Comment by mie-h** [comment]
> Awesome scripts and organization, thank you!
> 
> I created my all_prediction.jsonl file using your script on the notebook, and performed your model evaluation scripts on it. I modified a bit 'main' so it prints the harassment data and so the created files go into a folder named just like the jsonl file used in the script. I thought it was a good way to test the script with our various data and keep track of the differences. What do you think?
> 
> Screenshot 2023-12-19 at 09 04 38
> I also replaced our name with a variable as discussed last week.

Looks good. Are we interested in validated harassment or unvalidated harassment here?

**Review by sikieng — APPROVED** [review]

**Comment by sikieng** [comment]
> > Awesome scripts and organization, thank you!
> > I created my all_prediction.jsonl file using your script on the notebook, and performed your model evaluation scripts on it. I modified a bit 'main' so it prints the harassment data and so the created files go into a folder named just like the jsonl file used in the script. I thought it was a good way to test the script with our various data and keep track of the differences. What do you think?
> > Screenshot 2023-12-19 at 09 04 38
> > I also replaced our name with a variable as discussed last week.
> 
> Looks good. Are we interested in validated harassment or unvalidated harassment here?

Maybe we can try to do both of them? I can do this part and push into the PR. please let me know.

**Comment by LucileTech** [comment]
Could we create a new PR for the unvalidated harassment? Sikieng is up for trying, and maybe it would be cleaner as we already have a lot of changes here
If it's okay for you Mie I'll approve and merge this PR

**Review by LucileTech — APPROVED** [review]

**Pull request merged**
